# バージョンの記載がないければ最新のバージョンがインストールされる
name: flutter_catalog
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_riverpod:
  riverpod_annotation: ^2.6.1

  freezed:
  equatable:
  json_annotation:
  freezed_annotation:

  retrofit:

  shared_preferences:
  flutter_secure_storage:

  local_auth:

  go_router: ^14.6.3

  flutter_svg:

  simple_logger:
  dio: ^5.7.0
  hooks_riverpod: ^2.6.1
  video_player: ^2.9.2
  carousel_slider: ^5.0.0
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  custom_lint: ^0.6.5
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  melos: ^5.2.0
flutter:
  uses-material-design: true
